app/Modules/Pim/Http/Controllers/EmployeeDocumentsController.php
<?php

namespace App\Modules\Pim\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Modules\Pim\Repositories\Interfaces\EmployeeRepositoryInterface as EmployeeRepository;
use App\Modules\Pim\Repositories\Interfaces\EmployeeDocumentRepositoryInterface as EmployeeDocumentRepository;
use App\Modules\Settings\Repositories\Interfaces\DocumentTemplateRepositoryInterface as DocumentTemplateRepository;
use App\Modules\Pim\Http\Requests\EmployeeDocumentRequest;
use Illuminate\Http\Request;
use Datatables;
use PDF;

class EmployeeDocumentsController extends Controller
{
    private $employeeRepository;
    private $employeeDocumentRepository;

    public function __construct(
            EmployeeRepository $employeeRepository,
            EmployeeDocumentRepository $employeeDocumentRepository
        )
    {
        $this->employeeRepository = $employeeRepository;
        $this->employeeDocumentRepository = $employeeDocumentRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param  integer  unique identifier for the related employee resource
     * @return \Illuminate\Http\Response
     */
    public function index($employeeId)
    {
        $employee = $this->employeeRepository->getById($employeeId);
        $breadcrumb = [
            'parent_id' => $employeeId, 
            'parent_title' => $employee->first_name.' '.$employee->last_name,
            'parent_type' => get_user_role($employee->role)
        ];
        $accounts = $this->employeeDocumentRepository->getByMany(['user_id' => $employeeId])->get()->pluck('name','id');
        return view('pim::employee_documents.index', compact('breadcrumb', 'accounts'));
    }

    /**
     * Returns data for the resource list
     * 
     * @param  integer  unique identifier for the related employee resource
     * @return \Illuminate\Http\Response
     */
    public function getDatatable($employeeId)
    {
        return Datatables::of($this->employeeDocumentRepository->getQry([[
                'key' => 'user_id', 
                'operator' => '=', 
                'value' =>  $employeeId
            ]], ['id', 'name', 'attachment', 'user_id']))
            ->editColumn('attachment', function($record) {
                return '<a href="'.route('storage',$record->attachment).'">'.route('storage',$record->attachment).'</a>';
            })
            ->addColumn('actions', function($record){
                return view('includes._datatable_actions', [
                    'deleteUrl' => route('pim.employees.documents.destroy', [$record->user_id, $record->id]), 
                    'editUrl' => route('pim.employees.documents.edit', [$record->user_id, $record->id])
                ]);
            })
            ->removeColumn('user_id')
            ->make();
    }

    /**
     * Returns the form for generating document from template
     * 
     * @param  integer  unique identifier for the related employee resource
     * @return \Illuminate\Http\Response
     */
    public function generate($employeeId, DocumentTemplateRepository $documentTemplateRepository)
    {
        $employee = $this->employeeRepository->getById($employeeId);
        $breadcrumb = [
            'parent_id' => $employeeId, 
            'parent_title' => $employee->first_name.' '.$employee->last_name,
            'parent_type' => get_user_role($employee->role)
        ];
        $documents = $documentTemplateRepository->getByMany(['type' => $documentTemplateRepository->model::TYPE_PIM])->pluck('name','id');
        return view('pim::employee_documents.generate', compact('breadcrumb', 'documents'));
    }

    public function generateTemplateContent($employeeId, Request $request, DocumentTemplateRepository $documentTemplateRepository)
    {
        set_time_limit(-1);
        $bindings = template_toolbar();
        $document = $documentTemplateRepository->getById($request->get('document'));
        preg_match_all('/(%[a-z_]+\.[a-z_]+%)/', $document->template, $matches);
        $employee = $this->employeeRepository->getById($employeeId);
        foreach ($matches[1] as $key => $value) {
            $document->template = preg_replace('/'.$value.'/', $employee->{$bindings[trim($value, '%')]}, $document->template);
        }

        $pdf = PDF::loadView('pdf.default', ['content' => $document->template, 'details' => '']);
        return $pdf->download('document.pdf');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  integer  unique identifier for the related employee resource
     * @return \Illuminate\Http\Response
     */
    public function create($employeeId)
    {
        $employee = $this->employeeRepository->getById($employeeId);
        $breadcrumb = [
            'parent_id' => $employeeId, 
            'parent_title' => $employee->first_name.' '.$employee->last_name,
            'parent_type' => get_user_role($employee->role)
        ];
        return view('pim::employee_documents.create', compact('breadcrumb'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  integer  unique identifier for the related employee resource
     * @param  \App\Modules\Settings\Http\Requests\EmployeeDocumentRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store($employeeId, EmployeeDocumentRequest $request)
    {
        $documentData = $request->only(['name', 'description']) + ['user_id' => $employeeId];
        $attachment = $request->attachment->store('uploads/salaries');
        $documentData['attachment'] = $attachment;
        $documentData = $this->employeeDocumentRepository->create($documentData);
        $request->session()->flash('success', trans('app.pim.employees.documents.store_success'));
        return redirect()->route('pim.employees.documents.edit', [$employeeId, $documentData->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  integer  unique identifier for the related employee resource
     * @param  integer  unique identifier for the resource
     * @return \Illuminate\Http\Response
     */
    public function show($employeeId, $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  integer  unique identifier for the related employee resource
     * @param  integer  unique identifier for the resource
     * @return \Illuminate\Http\Response
     */
    public function edit($employeeId, $id)
    {
        $employee = $this->employeeRepository->getById($employeeId);
        $document = $this->employeeDocumentRepository->getById($id);
        $breadcrumb = [
            'parent_id' => $employee->id,
            'parent_title' => $employee->first_name.' '.$employee->last_name,
            'parent_type' => get_user_role($employee->role), 
            'id' => $document->id,
            'title' => $document->name
        ];
        return view('pim::employee_documents.edit', compact('document', 'breadcrumb'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  integer  unique identifier for the related employee resource
     * @param  integer  unique identifier for the resource
     * @param  \App\Modules\Settings\Http\Requests\EmployeeDocumentRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function update($employeeId, $id, EmployeeDocumentRequest $request)
    {
        $documentData = $request->only(['name', 'description']) + ['user_id' => $employeeId];
        if($request->hasFile('attachment')) {
            $attachment = $request->attachment->store('uploads/salaries');
            $documentData['attachment'] = $attachment;
        }
        $documentData = $this->employeeDocumentRepository->update($id, $documentData);
        $request->session()->flash('success', trans('app.pim.employees.documents.update_success'));
        return redirect()->route('pim.employees.documents.edit', [$employeeId, $documentData->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  integer  unique identifier for the related employee resource
     * @param  integer  unique identifier for the resource
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function destroy($employeeId, $id, Request $request)
    {
        $this->employeeDocumentRepository->delete($id);
        $request->session()->flash('success', trans('app.pim.employees.documents.delete_success'));
        return redirect()->route('pim.employees.documents.index', $employeeId);
    }
}

app/Modules/Pim/Http/Controllers/EmployeesController.php
<?php

namespace App\Modules\Pim\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Modules\Pim\Http\Requests\EmployeeRequest;
use App\Modules\Pim\Repositories\Interfaces\EmployeeRepositoryInterface as EmployeeRepository;
use Datatables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Mail\Mailer;
use Illuminate\Support\Facades\Route;
use GuzzleHttp\Client as Guzzle;

class EmployeesController extends Controller
{
    private $employeeRepository;

    public function __construct(EmployeeRepository $employeeRepository)
    {
        $this->employeeRepository = $employeeRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pim::employees.index');
    }

    /**
     * Display a list of the birthdays.
     *
     * @return array
     */
    public function birthdays(Request $request)
    {
        $items = $this->employeeRepository->getBirthdays($request->get('date'));
        return $items;
    }

    /**
     * Return data for the resource list
     *
     * @return \Illuminate\Http\Response
     */
    public function getDatatable()
    {
        return Datatables::of($this->employeeRepository->getCollection(
                [['key' => 'role', 'operator' => '=', 'value' => $this->employeeRepository->model::USER_ROLE_EMPLOYEE]],
                ['id', 'first_name', 'last_name', 'email']))
            ->addColumn('actions', function($employee){
                return view('includes._datatable_actions', [
                    'deleteUrl' => route('pim.employees.destroy', $employee->id),
                    'editUrl' => route('pim.employees.edit', $employee->id)
                ]);
            })
            ->make();
    }

    /**
     * Returns all employee details for using with select2
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function getSelectJson(Request $request)
    {
        return $this->employeeRepository->getSelect2Data($request->get('q'), $request->get('page'));
    }

    /**
     * Returns the selected employee details for using with select2
     * @param  integer $id the primary key of the selected employee
     * @return \Illuminate\Http\Response
     */
    public function getSelect2Selection($id)
    {
        return $this->employeeRepository->getSelect2Selection($id);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pim::employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Modules\Pim\Http\Requests\EmployeeRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        $employeeData = $request->all();
        $employeeData['role'] = $this->employeeRepository->model::USER_ROLE_EMPLOYEE;
        $employeeData = $this->employeeRepository->create($employeeData);
        $this->sendPassword($employeeData->id);


        if(env('ZAPIER_BIRTHDAY_HOOK')) {
            $client = new Guzzle();
            $client->request('POST', env('ZAPIER_BIRTHDAY_HOOK'), [
                'json' => [
                    'date' => $employeeData->birth_date,
                    'name' => $employeeData->first_name.' '.$employeeData->last_name,
                ],
            ]);
        }

        $request->session()->flash('success', trans('app.pim.employees.store_success'));

        return redirect()->route('pim.employees.edit', $employeeData->id);
    }

    public function resendPassword($id, Request $request)
    {
        $this->sendPassword($id);
        $request->session()->flash('success', trans('app.pim.employees.pass_success'));
        return redirect()->back();
    }

    private function sendPassword($id)
    {
        $password = rand();
        $employeeData = $this->employeeRepository->update($id, ['password' => bcrypt($password)]);
        $data['email'] = [
            'name' => $employeeData->first_name,
            'system' => config('app.name'),
            'url' => url('/'),
            'email' =>  $employeeData->email,
            'password' => $password, 
            'change_pass_route' => url('password/reset'),
            'signature' => env('APP_NAME', 'HRM')
            ];
        Mail::send('emails.employee-login-password', $data, function($message) use ($employeeData)
        {
            $message->subject(trans('emails.employee_login.subject', ['name' => config('app.name')]));
            $message->to($employeeData['email']);
        });
    }

    /**
     * Display the specified resource.
     *
     * @param  integer  unique identifier for the resource
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  integer  unique identifier for the resource
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = $this->employeeRepository->getById($id);
        if($employee->role == $this->employeeRepository->model::USER_ROLE_CANDIDATE) {
            return redirect()->route('pim.candidates.edit', $id);
        }
        return view('pim::employees.edit', ['employee' => $employee, 'breadcrumb' => ['title' => $employee->first_name.' '.$employee->last_name, 'id' => $employee->id]]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  integer  unique identifier for the resource
     * @param  \App\Modules\Pim\Http\Requests\EmployeeRequest $request
     * @return \Illuminate\Http\Response
     */
    public function update($id, EmployeeRequest $request)
    {
        $employeeData = $this->employeeRepository->update($id, $request->all());
        $request->session()->flash('success', trans('app.pim.employees.update_success'));
        return redirect()->route('pim.employees.edit', $employeeData->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  integer  unique identifier for the resource
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        $this->employeeRepository->delete($id);
        $request->session()->flash('success', trans('app.pim.employees.delete_success'));
        return redirect()->route('pim.employees.index');
    }
}

app/Modules/Pim/resources/views/employee_documents/_form.blade.php
<div class="form-group">
    {!! Form::label('name', trans('app.pim.employees.documents.name').':', ['class' => 'col-sm-3']) !!}
    <div class="col-sm-6">
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    </div>
</div>
<div class="form-group">
    {!! Form::label('description', trans('app.pim.employees.documents.description').':', ['class' => 'col-sm-3']) !!}
    <div class="col-sm-6">
        {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
    </div>
</div>
<div class="form-group">
    {!! Form::label('attachment', trans('app.pim.employees.documents.attachment'), ['class' => 'col-sm-3']) !!}
    <div class="col-sm-6">
        {!! Form::input('file', 'attachment', null, ['class' => 'form-control']) !!}
    </div>
</div>
@if(@$document->attachment)
<div class="form-group">
    <div class="col-sm-6 col-sm-offset-3">
        <a href="{{route('storage',$document->attachment)}}">{{trans('app.pim.employees.salaries.attachment')}}</a>
    </div>
</div>
@endif
@include('errors._form-errors')
<hr>
<div class="form-group">
    <div class="col-sm-6 col-sm-offset-3">
        <a href="{{route('pim.employees.documents.index', Route::input('employeeId'))}}" class="btn btn-default">{{trans('app.cancel')}}</a>
        {!! Form::submit($submitName, ['class' => 'btn btn-primary']) !!}
    </div>
</div>

app/Modules/Pim/resources/views/employee_documents/create.blade.php
@extends('layouts.main')
@section('content')
<div class="row">
    <div class="col-sm-12">
        <div class="custom-panel">
            <div class="custom-panel-heading">{{trans('app.pim.employees.documents.add_new')}}</div>
            {!! Form::open(['route' => ['pim.employees.documents.store', Route::input('employeeId')], 'class' => 'form-horizontal', 'enctype' => 'multipart/form-data']) !!}
                @include('pim::employee_documents._form', ['submitName' => trans('app.submit')])
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

app/Modules/Pim/resources/views/employee_documents/edit.blade.php
@extends('layouts.main')
@section('content')
<div class="row">
    <div class="col-sm-12">
        <div class="custom-panel">
            <div class="custom-panel-heading">{{trans('app.pim.employees.documents.edit_details')}}</div>
            {!! Form::model($document, ['method' => 'PUT', 'route' => ['pim.employees.documents.update', Route::input('employeeId'), $document->id], 'class' => 'form-horizontal', 'enctype' => 'multipart/form-data']) !!}
                @include('pim::employee_documents._form', ['submitName' => trans('app.submit')])
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

app/Modules/Pim/resources/views/employee_documents/generate.blade.php
@extends('layouts.main')
@section('content')
<div class="row">
    <div class="col-sm-12">
        <div class="custom-panel">
            <div class="custom-panel-heading">{{trans('app.pim.employees.documents.generate')}}</div>
            {!! Form::open(['id' => 'form-generate', 'class' => 'form-horizontal', 'route' => ['pim.employees.documents.template_content', Route::input('employeeId')]]) !!}
                <div class="form-group">
                    {!! Form::label('document', trans('app.pim.employees.documents.templates.document'), ['class' => 'col-sm-3']) !!}
                    <div class="col-sm-6">
                        {!! Form::select('document', $documents, null, ['class' => 'form-control', 'id' => 'document']) !!}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-6 col-sm-offset-3">
                        {!! Form::submit(trans('app.pim.employees.documents.btn_generate'), ['class' => 'btn btn-primary']) !!}
                    </div>
                </div>
                <div id="preview"></div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

app/Modules/Pim/resources/views/employee_documents/index.blade.php
@extends('layouts.main')
@section('content')
<div class="row">
    <div class="col-sm-12">
        <a href="{{route('pim.employees.documents.generate', Route::input('employeeId'))}}" class="btn btn-default pull-left">{{trans('app.pim.employees.documents.generate')}}</a>
        <a href="{{route('pim.employees.documents.create', Route::input('employeeId'))}}" class="btn btn-primary pull-right">{{trans('app.pim.employees.documents.add_new')}}</a>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="custom-panel">
            <div class="custom-panel-heading">{{trans('app.pim.employees.documents.main')}}</div>
            <table class="table table-bordered table-hover" id="documentsTable">
                <thead>
                    <th>{{trans('app.id')}}</th>
                    <th>{{trans('app.pim.employees.documents.name')}}</th>
                    <th>{{trans('app.pim.employees.documents.attachment')}}</th>
                    <th></th>
                </thead>
                <tfoot>
                    <th>
                        <input type="text" placeholder="{{trans('app.id')}}"/>
                    </th>
                    <th>
                        <input type="text" placeholder="{{trans('app.pim.employees.documents.name')}}"/>
                    </th>
                    <th></th>
                    <th></th>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection
@section('additionalCSS')
<link rel="stylesheet" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">
@endsection
@section('additionalJS')
<script src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function(){
        var table = $('#documentsTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ route("pim.employees.documents.datatable", Route::input("employeeId"))}}',
            columns: [
                {data: 0, name: 'id'},
                {data: 1, name: 'name'},
                {data: 2, name: 'attachment', sortable: false, searchable: false},
                {data: 3, name: 'actions', sortable: false, searchable: false}
            ]
        });
        table.columns().every(function () {
            var that = this;
            $('input', this.footer()).on( 'keyup change', function () {
                if (that.search() !== this.value) {
                    that.search(this.value).draw();
                }
            });
        });
    });
</script>
@endsection